// ============ Cinematography Presets ============
// Preset options for shot metadata dropdown selectors.
// Each category maps to a field key used in short objects.

const PRESETS = {
    shotType: [
        { value: '环境全景 (environment)',   label: '环境全景 (environment)' },
        { value: '建立镜头 (establishing)',   label: '建立镜头 (establishing)' },
        { value: '行走 (walking)',           label: '行走 (walking)' },
        { value: '对话 (dialogue)',          label: '对话 (dialogue)' },
        { value: '独白 (monologue)',         label: '独白 (monologue)' },
        { value: '反应 (reaction)',          label: '反应 (reaction)' },
        { value: '互动 (interaction)',       label: '互动 (interaction)' },
        { value: '魔法/特效 (magic)',        label: '魔法/特效 (magic)' },
        { value: '战斗 (battle)',            label: '战斗 (battle)' },
        { value: '追逐 (chase)',             label: '追逐 (chase)' },
        { value: '过渡 (transition)',        label: '过渡 (transition)' },
        { value: '蒙太奇 (montage)',         label: '蒙太奇 (montage)' },
        { value: '插入特写 (insert)',        label: '插入特写 (insert)' },
        { value: '闪回 (flashback)',         label: '闪回 (flashback)' },
    ],

    emotion: [
        { value: '恐惧/不安',   label: '恐惧/不安' },
        { value: '威严/力量',   label: '威严/力量' },
        { value: '神秘/好奇',   label: '神秘/好奇' },
        { value: '孤独/渺小',   label: '孤独/渺小' },
        { value: '温暖/友情',   label: '温暖/友情' },
        { value: '愤怒/冲突',   label: '愤怒/冲突' },
        { value: '觉醒/顿悟',   label: '觉醒/顿悟' },
        { value: '仪式/庄严',   label: '仪式/庄严' },
        { value: '追逐/逃亡',   label: '追逐/逃亡' },
        { value: '悲伤/失落',   label: '悲伤/失落' },
        { value: '欢乐/庆祝',   label: '欢乐/庆祝' },
        { value: '紧张/悬疑',   label: '紧张/悬疑' },
        { value: '宁静/平和',   label: '宁静/平和' },
        { value: '惊讶/震撼',   label: '惊讶/震撼' },
        { value: '浪漫/柔情',   label: '浪漫/柔情' },
    ],

    cameraMovement: [
        { value: '固定机位 (Static)',              label: '固定机位 (Static)' },
        { value: '慢推 (Dolly In, slow)',          label: '慢推 (Dolly In, slow)' },
        { value: '快推 (Dolly In, fast)',          label: '快推 (Dolly In, fast)' },
        { value: '慢拉 (Dolly Out, slow)',         label: '慢拉 (Dolly Out, slow)' },
        { value: '快拉 (Dolly Out, fast)',         label: '快拉 (Dolly Out, fast)' },
        { value: '希区柯克变焦 (Dolly Zoom In)',    label: '希区柯克变焦 (Dolly Zoom In)' },
        { value: '慢升 (Crane Up, slow)',          label: '慢升 (Crane Up, slow)' },
        { value: '慢降 (Crane Down, slow)',        label: '慢降 (Crane Down, slow)' },
        { value: '平滑左摇 (Pan Left, smooth)',     label: '平滑左摇 (Pan Left, smooth)' },
        { value: '平滑右摇 (Pan Right, smooth)',    label: '平滑右摇 (Pan Right, smooth)' },
        { value: '慢仰 (Tilt Up, slow)',           label: '慢仰 (Tilt Up, slow)' },
        { value: '慢俯 (Tilt Down, slow)',         label: '慢俯 (Tilt Down, slow)' },
        { value: '弧形左移 (Arc Left, smooth)',     label: '弧形左移 (Arc Left, smooth)' },
        { value: '弧形右移 (Arc Right, smooth)',    label: '弧形右移 (Arc Right, smooth)' },
        { value: '手持晃动 (Handheld)',             label: '手持晃动 (Handheld)' },
        { value: '稳定跟踪 (Tracking, steady)',     label: '稳定跟踪 (Tracking, steady)' },
        { value: '慢变焦推近 (Zoom In, slow)',      label: '慢变焦推近 (Zoom In, slow)' },
        { value: '慢变焦拉远 (Zoom Out, slow)',     label: '慢变焦拉远 (Zoom Out, slow)' },
        { value: '慢环绕 (Orbit, slow)',            label: '慢环绕 (Orbit, slow)' },
    ],

    cameraAngle: [
        { value: '平视 (Eye-level)',         label: '平视 (Eye-level)' },
        { value: '仰拍 (Low Angle)',         label: '仰拍 (Low Angle)' },
        { value: '俯拍 (High Angle)',        label: '俯拍 (High Angle)' },
        { value: '荷兰角 (Dutch Angle)',      label: '荷兰角 (Dutch Angle)' },
        { value: '鸟瞰 (Bird\'s Eye)',       label: '鸟瞰 (Bird\'s Eye)' },
        { value: '蚁视 (Worm\'s Eye)',       label: '蚁视 (Worm\'s Eye)' },
        { value: '过肩 (Over-the-shoulder)',  label: '过肩 (Over-the-shoulder)' },
        { value: '第一人称视角 (POV)',         label: '第一人称视角 (POV)' },
        { value: '特写 (Close-up)',           label: '特写 (Close-up)' },
        { value: '大特写 (Extreme Close-up)', label: '大特写 (Extreme Close-up)' },
        { value: '中景 (Medium Shot)',        label: '中景 (Medium Shot)' },
        { value: '全景 (Wide Shot)',          label: '全景 (Wide Shot)' },
        { value: '远景 (Extreme Wide)',       label: '远景 (Extreme Wide)' },
        { value: '双人镜头 (Two-shot)',       label: '双人镜头 (Two-shot)' },
    ],

    lighting: [
        { value: '黄金时段暖光 (Golden-hour)',    label: '黄金时段暖光 (Golden-hour)' },
        { value: '低调暗影 (Low-key)',            label: '低调暗影 (Low-key)' },
        { value: '高调明亮 (High-key)',           label: '高调明亮 (High-key)' },
        { value: '轮廓光 (Rim Light)',            label: '轮廓光 (Rim Light)' },
        { value: '体积光 (Volumetric)',           label: '体积光 (Volumetric)' },
        { value: '丁达尔效应 (God-rays)',         label: '丁达尔效应 (God-rays)' },
        { value: '月光冷蓝 (Moonlight)',          label: '月光冷蓝 (Moonlight)' },
        { value: '霓虹赛博 (Neon)',               label: '霓虹赛博 (Neon)' },
        { value: '烛光 (Candlelight)',            label: '烛光 (Candlelight)' },
        { value: '阴天柔光 (Overcast)',           label: '阴天柔光 (Overcast)' },
        { value: '高对比偏红 (High-contrast)',     label: '高对比偏红 (High-contrast)' },
        { value: '剪影逆光 (Silhouette)',         label: '剪影逆光 (Silhouette)' },
        { value: '三点布光 (Three-point)',        label: '三点布光 (Three-point)' },
    ],
};

export default PRESETS;
